Dark/scheme toggle
MarikaGK/filmoteka-js-team-project pull request #48
Opened 2023-04-19 18:32 UTC by Lukasz996

test position /  test keyframes

2023-04-19 20:04 UTC, MarcinBolt requested changes
Łukasz dużo do zmian:
1. Zmiana nazwy pliku scss.
2. zmiana klasy toggle na konkretną, by było wiadomo, od czego to jest.
3. Oprogramowanie w JS, dodanie pliku np.dark-mode-switch.js do folderu js/utils/:
  3.1.  Złapanie checkbox'a, jako z DOM.
  3.2. Oprogramowanie jego stanów (TRUE/FALSE) - co ma się dziać 
    - TRUE: wstrzykiwanie klasy modyfikującej (np. movie-card--dark-mode-style) do wszystkich potrzebnych elementów, 
    - FALSE: usuwanie klasy modyfikującej ze wszystkich zmodyfikowanych wcześniej elementów, 
4. Animacja switch'a nie działa.
5. Jak użyłeś input type checkbox do zmiany NORMAL/DARK MODE, to on musi być dostępny do kliknięcia na całym przełączniku, a nie tylko na stronie lewej. Użytkownik klikając go z prawej strony będzie się wkurzał, że nie działa.
6. Import do poprawy, bo inaczej będzie się nazywał plik. Pamiętaj, że ten import musi być na końcu, by zastępował style domyślne przy włącaniu trybu ciemnego.

2023-04-19 20:04 UTC, MarcinBolt commented on src/sass/index.scss
> +@import './base/scheme-toggle';
Import będzie również do poprawy, bo zmieni się nazwa pliku.
Pamiętaj!!! Ten import MUSI być na końcu, bo on ma zastępować inne style jak pojawi się klasa modyfikująca przy DARK MODE.

2023-04-20 18:21 UTC, Lukasz996 commented
Jutro będę działać z keyframes i z usunięciem checkbox-a

2023-04-23 22:04 UTC, MarcinBolt approved these changes

2023-04-23 22:06 UTC, merged