add_background_images
MarikaGK/filmoteka-js-team-project pull request #9
Opened 2023-04-14 10:02 UTC by maciejkudej

Add images for header (for home and for watched leyout) remove test comment from index.js

2023-04-14 10:21 UTC, MarcinBolt commented
Maciej, tak na pierwszy rzut oka widzę powielone nazwy rozszerzeń plików - to trzebaby poprawić. Używałeś jakiegoś optymalizatora obrazów?

2023-04-14 22:56 UTC, MarcinBolt requested changes
Maciej, popraw proszę nazwy plików, bo występują dwa razy rozszerzenia (.png.png). 
Czy używałeś na nich jakiegoś optymalizatora obrazów, by zostały zmniejszone?

2023-04-15 09:08 UTC, maciejkudej commented
Hej, dzięki za zwrocenie uwagi, zoptymalizowałem grafikę zdjec w squooshu,  nazwy poprawiłem i dodałem ikony SVG :)

2023-04-15 12:19 UTC, MarcinBolt approved these changes
icons.svg jest jeszcze do optymalizacji, ale zatwierdzam, żeby sprawdzić użycie ikonek.
Potem trzeba będzie go zoptymalizować.

2023-04-15 12:20 UTC, merged

2023-04-15 12:29 UTC, MarcinBolt commented
Maciek, dobra robota!